document.writeln("<ul>");
document.writeln("<li>");
document.writeln("<a href=\'http://www.ujiabb.com/\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'优家宝贝加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/FBKjgtuQQP.gif\' alt=\'优家宝贝加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'http://www.henanshuihu.com/\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'梁山烤肉加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/sZrxxJNVbP.gif\' alt=\'梁山烤肉加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'http://www.chinadee.com/\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'德意电器加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/TNKaBtEZtR.gif\' alt=\'德意电器加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'http://www.chinadee.com/\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'民间创富加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/GUCTAqyPdX.gif\' alt=\'民间创富加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'http://bd-jp6k.zwxd08.cn/mbhl/pc/?bd_vid=5177539463568334593\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'卡佩王朝烘培加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/uySlSaQxNL.gif\' alt=\'卡佩王朝烘培加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'https://www.qj.com.cn/brand/dewdhg/shop/\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'东阿味道加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/kIYdMxVDqH.gif\' alt=\'东阿味道加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'http://www.51jam.com/mendian/17/2192.html\' target=\'_blank\' rel=\'nofollow\' target=\'_blank\' title=\'小童星儿童模特艺术加盟\'>");
document.writeln("<img src=\'https://cpt.viewsrc.stream/panswork/left/odGUhWPkoH.gif-100x80.gif\' alt=\'小童星儿童模特艺术加盟\' width=\'100\' height=\'80\'>");
document.writeln("</a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("");